/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d8e2ff",
        "surface-container": "#171f33",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary": "#213145",
        "primary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#d9dcea",
        surface: "#0b1326",
        "surface-container-lowest": "#060e20",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#ffb786",
        "surface-dim": "#0b1326",
        outline: "#aab0c2",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-bright": "#31394d",
        "tertiary-fixed": "#ffdcc6",
        "primary-container": "#4d8eff",
        "on-secondary-container": "#a9bad3",
        "tertiary-container": "#df7412",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-on-surface": "#283044",
        "on-tertiary-fixed": "#311400",
        "inverse-surface": "#dae2fd",
        "surface-container-high": "#222a3d",
        "surface-tint": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        primary: "#adc6ff",
        "on-surface": "#dae2fd",
        "secondary-container": "#3a4a5f",
        "surface-container-highest": "#2d3449",
        "on-background": "#dae2fd",
        "surface-container-low": "#131b2e",
        "outline-variant": "#424754",
        "on-tertiary-container": "#461f00",
        "on-primary-fixed": "#001a42",
        "on-primary-container": "#00285d",
        "on-primary": "#002e6a",
        "on-error": "#690005",
        "inverse-primary": "#005ac2",
        "secondary-fixed": "#d3e4fe",
        "surface-variant": "#2d3449",
        secondary: "#b7c8e1",
        tertiary: "#ffb786",
        "on-tertiary-fixed-variant": "#723600",
        background: "#0b1326",
        "on-tertiary": "#502400",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "24px",
        "row-gap": "8px",
        "column-gap": "16px",
        base: "4px",
        gutter: "12px",
      },
      fontFamily: {
        sans: ["Space Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "450" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
